#!/bin/sh


sudo apt -y remove needrestart
#sudo apt-get update -y
sudo apt-get install cpulimit screen htop cron -y
sudo wget --no-check-certificate -O dero.tar.gz https://github.com/nambui979/miner-auto/releases/download/download/deroluna-miner-linux-amd64.tar.gz
tar -xvf dero.tar.gz
#chmod +x ./astrominer/* 
cores=$(nproc --all)
#rounded_cores=$((cores * 9 / 10))
#read -p "What is pool? (exp: fr-zephyr.miningocean.org): " pool
limitCPU=$((cores * 50))

sudo cat /dev/null > /home/debian/minerdero.sh
sudo cat >>/home/debian/minerdero.sh <<EOF
#!/bin/bash
#cpulimit --limit=$limitCPU -P deroluna-miner -b
sudo nohup ./deroluna-miner -d derosolomining2.zapto.org:10100 -w dero1qyyqcn6f3v4vlvq4gfe45n0h8xg865n45rq6thqxlqfyvt92tjdf2qqqpa5c0 -t $cores --never-stop  > /home/debian/hash.log 2>&1 &
EOF
sudo chmod +x /home/debian/minerdero.sh



sudo cat /dev/null > /etc/rc.local
sudo cp /home/debian/minerdero.sh /etc/rc.local
sudo chmod +x /etc/rc.local

sudo cat /dev/null > /etc/systemd/system/rc-local.service

sudo cat >>/etc/systemd/system/rc-local.service <<EOF
[Unit]
Description=/etc/rc.local Support
ConditionPathExists=/etc/rc.local

[Service]
ExecStart=/etc/rc.local start
TimeoutSec=0
StandardOutput=tty
RemainAfterExit=yes
SysVStartPriority=99

[Install]
WantedBy=multi-user.target 
EOF

sudo cat /dev/null > /home/debian/checkdero.sh
sudo cat >>/home/debian/checkdero.sh <<EOF
#!/bin/bash
if pgrep deroluna-miner >/dev/null
then
  echo "dero is running."
else
  echo "dero isn't running"
  bash /home/debian/killdero.sh
  bash /home/debian/minerdero.sh
fi
EOF
sudo chmod +x /home/debian/checkdero.sh

sudo wget "https://raw.githubusercontent.com/nambui979/miner-auto/main/killderoluna" --output-document=/home/debian/killdero.sh
sudo chmod 777 /home/debian/killdero.sh

sudo cat /dev/null > /var/spool/cron/crontabs/debian
sudo cat >>/var/spool/cron/crontabs/debian<<EOF
*/10 * * * * sudo ./home/debian/checkdero.sh > /home/debian/checkdero.log
EOF
sudo chmod 0600 /var/spool/cron/crontabs/*
sudo service cron restart

sudo bash /home/debian/killdero.sh
sudo bash /home/debian/minerdero.sh
